webtalk_init -webtalk_dir /home/avijit/study_material/Computer_Ogranisation_Lab/projects/assign_2_b/assign_2_b.sim/sim_1/behav/xsim/xsim.dir/tstb_RCA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 11 18:47:19 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2cdc439d-77ae-4272-bd46-148e5d3e57d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c658029f58b54fc09e48a8c385a9cf3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.7 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1284.777 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3209074356 -regid "" -xml /home/avijit/study_material/Computer_Ogranisation_Lab/projects/assign_2_b/assign_2_b.sim/sim_1/behav/xsim/xsim.dir/tstb_RCA_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/avijit/study_material/Computer_Ogranisation_Lab/projects/assign_2_b/assign_2_b.sim/sim_1/behav/xsim/xsim.dir/tstb_RCA_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/avijit/study_material/Computer_Ogranisation_Lab/projects/assign_2_b/assign_2_b.sim/sim_1/behav/xsim/xsim.dir/tstb_RCA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
